export const industriesOptions = [
  'Manufacturing (Automotive, Electronics, Consumer Goods)',
  'Construction & Engineering',
  'Agriculture & Farming',
  'Energy & Utilities (Oil & Gas, Renewable Energy)',
  'Telecommunications & Networking',
  'Pharmaceuticals & Healthcare',
  'Food & Beverage Production',
  'Technology & Software Development',
  'Aerospace & Defense',
  'Financial Services & Banking',
  'Retail & E-commerce',
  'Media & Entertainment',
  'Education & Training',
  'Environmental & Sustainability',
  'Government & Public Services',
  'Transportation & Logistics',
  'Hospitality & Tourism',
  'Real Estate & Property Development',
  'Automotive & Transportation',
  'Creative & Design Industries',
];
